[build]
command = "./build.sh"
functions = "functions"
publish = "public"

[build.environment]
GO_IMPORT_PATH = "github.com/0x111/serverless-sample"
GO111MODULE = "on"

[[redirects]]
from = "/today"
to = "/.netlify/functions/gateway/:splat"
status = 200